const swaggerAutogen = require("swagger-autogen")();

const outputFile = "./swagger_output.json";
const endpointsFiles = ["./server.js"];

const doc = {
  info: {
    version: "1.0.0",
    title: "TDFL API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  tags: [
    {
      name: "User",
    },
    {
      name: "Post",
    },
    {
      name: "Friend",
    },
  ],
  definitions: {
    User: {
      name: "testing",
      email: "testing@testing.com",
    },
    Post: {
      id: 2,
      title: "Testing Post",
    },
  },
};

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require("./server.js");
});
